/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay_ms(uint32_t ms)
{
	SysTick->LOAD = (16000-1);


	SysTick->VAL=0;

	SysTick->CTRL |= (1U<<0) | (1U<<2);

	for(uint32_t i = 0; i<ms; i++)
	{
		while(!(SysTick->CTRL & (1U<<16)))
				{
			__asm("nop");
				}
	}
	SysTick->CTRL = 0;
}

void usart2_tx_init(void)
{
	RCC->AHB1ENR |= (1U << 0);
	RCC->APB1ENR |= (1U << 17);

	GPIOA->MODER &= ~(3U << (2 * 2));
	GPIOA->MODER |= (2U << (2 * 2));


	GPIOA->AFR[0] &= ~(0xFU << (2 * 4));
	GPIOA->AFR[0] |= (7U << (2 * 4));


	USART2->BRR = 0x8B;


	USART2->CR1 = (1U << 3) | (1U << 13);
}

void usart2_write_char(char ch)
{
	while (!(USART2->SR & (1U << 7)))
	{
		__asm("nop");
	}

	USART2->DR = (ch & 0xFF);
}

void usart2_print(char *str)
{
	while (*str)
	{
		usart2_write_char(*str++);
	}
}

int __io_putchar(int ch)
{
	usart2_write_char((char)ch);
	return ch;
}

int _write(int file, char *ptr, int len)
{
	for (int i=0; i < len; i++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}


int main(void)
{
	RCC->AHB1ENR |= (1U<<0);

	GPIOA->MODER &= ~(3U << (5*2));
	GPIOA->MODER |=(1U<<(5*2));
	usart2_tx_init();

	int sayac = 0;
	float voltaj = 3.3f;

	printf("--- STM32F446RE Bare-Metal Printf Testi ---");

	while(1)
	{
		GPIOA->BSRR = (1U << 5);
		printf("Dongu : %d, LED Durumu Acik, Referans Voltaj: %.1f V \r\n", sayac, voltaj);
		delay_ms(1000);

		GPIOA->BSRR = (1U << (5+16));
		printf("Dongu %d, LED Durumu kapali\r\n", sayac);
		delay_ms(1000);

		sayac++;
	}
	return 0;
}
