/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay_ms(uint32_t ms)
{
	SysTick->LOAD = (16000-1);

	SysTick->VAL=0;

	SysTick->CTRL |= (1U<<0) | (1U<<2);

	for(uint32_t i = 0; i<ms; i++)
	{
		while(!(SysTick->CTRL & (1U<<16)))
				{
			__asm("nop");
				}
	}
	SysTick->CTRL = 0;
}

volatile uint32_t basma_sayisi = 0;

void usart2_tx_init(void)
{
	RCC->AHB1ENR |= (1U << 0);
	RCC->APB1ENR |= (1U << 17);

	GPIOA->MODER &= ~(3U << (2 * 2));
	GPIOA->MODER |= (2U << (2 * 2));


	GPIOA->AFR[0] &= ~(0xFU << (2 * 4));
	GPIOA->AFR[0] |= (7U << (2 * 4));


	USART2->BRR = 0x8B;


	USART2->CR1 = (1U << 3) | (1U << 13);
}

void usart2_write_char(char ch)
{
	while (!(USART2->SR & (1U << 7)))
	{
		__asm("nop");
	}

	USART2->DR = (ch & 0xFF);
}

void usart2_print(char *str)
{
	while (*str)
	{
		usart2_write_char(*str++);
	}
}

int __io_putchar(int ch)
{
	usart2_write_char((char)ch);
	return ch;
}

int _write(int file, char *ptr, int len)
{
	for (int i=0; i < len; i++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}

void pc13_kesme_init(void)
{
	RCC->AHB1ENR |= (1U << 2);
	RCC->APB2ENR |= (1U << 14);

	GPIOC->MODER &= ~(3U << (13*2));

	SYSCFG->EXTICR[3] &= ~(0xFU << 4);
	SYSCFG->EXTICR[3] |= (0x2U << 4);

	EXTI->IMR |= (1U << 13);
	EXTI->FTSR |= (1U << 13);

	NVIC->ISER[1] = (1U << 8);

	void EXTI15_10_IRQHandler(void)
	{
		if (EXTI->PR & (1U << 13))
		{
			EXTI->PR |= (1U << 13);

			GPIOA->ODR ^=(1U << 5);

			basma_sayisi++;
		}
	}
}

void tim2_pwm_init(void)
{
	RCC->AHB1ENR |= (1U << 0); //GPIOA
	RCC->APB1ENR |= (1U << 0); //TIM2

	GPIOA->MODER &= ~(3U << (5 * 2));
	GPIOA->MODER |= (2U << (5 * 2));

	GPIOA->AFR[0] &= ~(0xFU << (5 * 4));
	GPIOA->AFR[0] |= (1U << (5 * 4));

	TIM2->PSC = 16-1; // 15MHZ PSC= Saat frekansını yavaslatır
	TIM2->ARR = 1000 - 1; //Sayacın kaca kadar sayacagini sıfırlanacağını belirler

	TIM2->CCMR1 &= ~(7U << 4);
	TIM2->CCMR1 |= (6U << 4);

	TIM2->CCMR1 |= (1U << 3);

	TIM2->CCER |= (1U << 0);

	TIM2->EGR |= (1U << 0);

	TIM2->CCR1 = 0;

	TIM2->CR1 |= (1U << 0);
}

int main(void)
{
	tim2_pwm_init();

	while(1)
	{
		for(int duty = 0; duty <= 1000; duty += 20)
		{
			TIM2->CCR1 = duty;
			delay_ms(15);
		}
		for(int duty = 1000; duty>=0; duty-=20)
		{
			TIM2->CCR1 = duty;
			delay_ms(15);
		}
	}
	return 0;
}

